name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ai_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Get PR Diff
        id: get_diff
        run: |
          echo "##[set-output name=diff;]$(git diff origin/main...HEAD)" 

      - name: Install Node Dependencies
        run: |
          npm install openai

      - name: AI Code Review
        run: |
          node .github/scripts/ai-review.js "${{ steps.get_diff.outputs.diff }}"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
