name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: 'Install root dependencies'
        run: npm ci
  
      - name: 'Lint root'
        run: npm run lint
  
      - name: 'Type Check root'
          run: npm run type-check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - app
          - firebase/functions
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json
        working-directory: ${{ matrix.package }}

      - name: debug
        run: |
            echo "Running inside: $(pwd)"
        working-directory: ${{ matrix.package }}
      
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ matrix.package }}

      - name: Run tests
        run: npm run test
        working-directory: ${{ matrix.package }}