name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Functions Tests
      - name: Test Functions
        run: |
          cd firebase/functions
          npm ci --ignore-scripts
          npx jest --config jest.config.ts

      # App Tests
      - name: Test App
        run: |
          cd app
          npm ci --ignore-scripts
          npx jest --passWithNoTests 