name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '22'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      # Install root dependencies
      - name: Install root dependencies
        run: |
          npm pkg delete scripts.prepare
          npm ci
          
      # Test App
      - name: Test App
        run: |
          cd app
          npm pkg delete scripts.prepare
          npm ci
          npm run test
          
      # Test Functions
      - name: Test Functions
        run: |
          cd firebase/functions
          npm pkg delete scripts.prepare
          npm ci
          npm run test
          
      # Run linting and type checking
      - name: Lint and Type Check
        run: |
          npm run lint
          npm run type-check 